// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlmA47Fz5NSn8NzdIR_mbSXPaLyyYKyM',
    appId: '1:706130879164:web:79a84229aef7f77db9a6b9',
    messagingSenderId: '706130879164',
    projectId: 'login-b75f9',
    authDomain: 'login-b75f9.firebaseapp.com',
    storageBucket: 'login-b75f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_OH0UrPYJuMpr2SXW_pkboOzPXpEBc7g',
    appId: '1:706130879164:android:dbb73c6bb8d3e273b9a6b9',
    messagingSenderId: '706130879164',
    projectId: 'login-b75f9',
    storageBucket: 'login-b75f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPXTu86-8o-WnDkZ9pf-FSzF7fEIOmd8Q',
    appId: '1:706130879164:ios:aa62d06bc990a205b9a6b9',
    messagingSenderId: '706130879164',
    projectId: 'login-b75f9',
    storageBucket: 'login-b75f9.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPXTu86-8o-WnDkZ9pf-FSzF7fEIOmd8Q',
    appId: '1:706130879164:ios:aa62d06bc990a205b9a6b9',
    messagingSenderId: '706130879164',
    projectId: 'login-b75f9',
    storageBucket: 'login-b75f9.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPlmA47Fz5NSn8NzdIR_mbSXPaLyyYKyM',
    appId: '1:706130879164:web:d23c6a83ada4cf15b9a6b9',
    messagingSenderId: '706130879164',
    projectId: 'login-b75f9',
    authDomain: 'login-b75f9.firebaseapp.com',
    storageBucket: 'login-b75f9.firebasestorage.app',
  );

}