import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'pages/login_page.dart';
import 'pages/signup_page.dart';
import 'pages/notes_page.dart';
import 'firebase_options.dart'; // generated by flutterfire

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // <-- required on Web
  );
  runApp(const NotesApp());
}


class NotesApp extends StatelessWidget {
const NotesApp({super.key});


@override
Widget build(BuildContext context) {
return MaterialApp(
debugShowCheckedModeBanner: false,
title: 'Notes App',
theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.indigo),
initialRoute: '/',
routes: {
'/': (context) => const AuthGate(),
'/login': (context) => const LoginPage(),
'/signup': (context) => const SignupPage(),
'/notes': (context) => const NotesPage(),
},
);
}
}


class AuthGate extends StatelessWidget {
const AuthGate({super.key});


@override
Widget build(BuildContext context) {
return StreamBuilder<User?>(
stream: FirebaseAuth.instance.authStateChanges(),
builder: (context, snapshot) {
if (snapshot.connectionState == ConnectionState.waiting) {
return const Scaffold(
body: Center(child: CircularProgressIndicator()),
);
}
if (snapshot.hasData) {
return const NotesPage();
} else {
return const LoginPage();
}
},
);
}
}